# Generated by Django 2.0.2 on 2018-04-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade_técnica', models.DecimalField(decimal_places=1, max_digits=2)),
                ('inovacao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('resultados', models.DecimalField(decimal_places=1, max_digits=2)),
                ('metodologia', models.DecimalField(decimal_places=1, max_digits=2)),
                ('adequacao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('media', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Avaliador'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ManyToManyField(to='notas.Autor'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Avaliacao'),
        ),
    ]
