# Generated by Django 2.0.2 on 2018-04-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='avaliador',
            field=models.ManyToManyField(to='notas.Avaliador'),
        ),
    ]
