# Generated by Django 2.0.2 on 2018-04-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_artigo_avaliador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='avaliador',
        ),
    ]
